spring.datasource.url=jdbc:postgresql://localhost:5432/ulbi
spring.datasource.username=postgres
spring.datasource.password=1111

# deleting and creating DB after each restarting of APP
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create-drop

#  show sql comand in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#next line add error message from exeption to header response
server.error.include-message=always

# JWT Configuration
jwt.secret=a7bcd6e8f9g0h1i2j3k4l5m6n7o8p9q0r1s2t3u4v5w6x7y8z9a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5
jwt.accesExpiration=300
jwt.refreshExpiration=86400

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nodeMailerStud@gmail.com
spring.mail.password=uobl xxkm ecwp ygek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true