spring.datasource.url=jdbc:postgresql://localhost:5432/ulbi
spring.datasource.username=postgres
spring.datasource.password=1111

# deleting and creating DB after each restarting of APP
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create-drop

#  show sql comand in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#next line add error message from exeption to header response
server.error.include-message=always

# JWT Configuration
jwt.secret=your-secret-key-here-make-it-long-and-secure
jwt.expiration=86400